block.10001=grass tall_grass fern large_fern wheat carrots potatoes beetroots seagrass sweet_berry_bush
block.10002=oak_leaves birch_leaves spruce_leaves jungle_leaves acacia_leaves dark_oak_leaves mangrove_leaves cherry_leaves azalea_leaves flowering_azalea_leaves
block.10003=water flowing_water
block.10004=torch wall_torch lantern glowstone shroomlight campfire fire magma_block
block.10005=soul_torch soul_wall_torch soul_lantern soul_fire sea_lantern sea_pickle
