profile.LOW=SHADOW_QUALITY=1 VL_SAMPLES=6 SHAFT_SAMPLES=8 SSR_STEPS=12 NEBULA_OCTAVES=2 ANTIALIASING=1
profile.MED=SHADOW_QUALITY=2 VL_SAMPLES=12 SHAFT_SAMPLES=16 SSR_STEPS=24 NEBULA_OCTAVES=3 ANTIALIASING=2
profile.HIGH=SHADOW_QUALITY=3 VL_SAMPLES=24 SHAFT_SAMPLES=32 SSR_STEPS=48 NEBULA_OCTAVES=5 ANTIALIASING=2
screen=STYLE <profile> ANTIALIASING [ATMOS] [SURFACE] [QUALITY]
screen.ATMOS=CUSTOM_FOG VOLUMETRIC_LIGHT LIGHT_SHAFTS CUSTOM_CLOUDS NIGHT_NEBULA
screen.SURFACE=WAVING_PLANTS REFLECTIONS UNDERWATER_FX DYNAMIC_SHADOWS COLORED_BLOCKLIGHT
screen.QUALITY=SHADOW_QUALITY VL_SAMPLES SHAFT_SAMPLES SSR_STEPS NEBULA_OCTAVES
shadow.culling=true
